### PR TITLE
Initial flowdec op experiments

### PR DESCRIPTION
**Pull request by eric-czech**
Hey @bnorthan ,

I gave creating a TensorFlow-based deconvolution op a shot here and I think this is a reasonable start though I hit a wall when I went to test it on a GPU via java instead of python -- it turns out that the [maven artifact they currently have for linux to support GPUs](https://www.tensorflow.org/versions/master/install/install_java#gpu_support) (which is separate from the one used in imagej-tensorflow at the moment if you're familiar with it) doesn't currently include support for certain operations in the graphs I'm exporting from Python.

That was a bummer to find out and in the same vein, there is no support for Java + Windows + GPUs but that's likely coming up soon per [this issue](https://github.com/tensorflow/tensorflow/issues/16660).

Anyways I'll log the issue I ran into and hopefully that'll get remedied relatively soon but I'm not sure where that leaves me here.  It works fine on CPUs only and I was using test classes like you seemed to be (here's my [InteractiveDeconvolveTest](https://github.com/eric-czech/ops-experiments/blob/master/ops-experiments-tensorflow/src/test/java/net/imagej/ops/experiments/filter/deconvolve/InteractiveDeconvolveTest.java)) which works well enough.  It seems kind of pointless w/o GPU support though so I'd certainly understand if you'd rather just not have this in the repo until that's done.

Regardless it was an interesting experiment and perhaps worth revisiting when those TensorFlow issues get ironed out.  Thanks for setting up the framework for me to give it a try!

### CODE REVIEW

**Comment by eric-czech** [comment]
Hey @bnorthan , makes sense!  And as it turns out I was just being dumb and forgot to exclude the older versions of tensorflow artifacts from my maven build so this actually seems to work well now.

On an EC2 instance with a Tesla K40 it takes about 3-4 seconds to run 100 iterations on the cropped bars dataset you had in ops-experiments-main and I get results like this (50 iterations shown as well):

screen shot 2018-04-14 at 8 26 06 am

I had a few questions though:
- **GPU Conditional Dependencies** - The TensorFlow dependencies are a bit weird since you have to switch one of them based on whether or not you're [building for a system w/ a GPU](https://www.tensorflow.org/versions/master/install/install_java#gpu_support).  I did this with a build profile in the [pom](https://github.com/eric-czech/ops-experiments/blob/master/ops-experiments-tensorflow/pom.xml#L100) that defaults to the cpu-only version so that I had to specify ```-P gpu``` when testing.  Is there a better way to do that?
- **TensorFlow Versions** - I'm overriding the 1.2.0 version of TF pulled in by imagej-tensorflow (which I was using for those awesome Img <--> Tensor utilities) to 1.7.0 which is apparently critical since my TF graphs have ops not supported by 1.2.0.  Is there any reason not to update imagej-tensorflow since it looks like it's been a while?  Maybe a question for @ctrueden ?
- **Testing** - To do this on an AWS server with no GUI I was using something like this [CLI Test Class](https://github.com/eric-czech/ops-experiments/blob/master/ops-experiments-tensorflow/src/main/java/net/imagej/ops/experiments/filter/deconvolve/FlowdecCli.java) via the old ImageJ apis since I was getting lots of errors run attempting to use ```ij.ops()``` (something about no valid context available when running ```new ImageJ()```).  How do you do testing on Linux systems Brian?  I'm not sure if ops should be working for me on Amazon Linux with no graphics drivers or if that's just kind of an unsupported use case.

Otherwise, let me know if there's anything else I can do here!  I'm happy to amend this to styles, or preferences, or better utilize existing libraries -- whatever you think is best.

Also, I'm not sure what's up with the travis CI build error.  Is the "org.bytedeco.javacpp-presets" artifact for ```ops-experiments-main``` not being found like that something you've seen before?

**Comment by imagejan** [comment]
@eric-czech wrote:
>  Is there any reason not to update imagej-tensorflow?

`imagej-tensorflow-1.0.0` uses TensorFlow 1.6.0, see https://github.com/imagej/imagej-tensorflow/pull/6.
If you need 1.7.0, I think a pull request on that repository would be welcome.

**Comment by bnorthan** [comment]
> How do you do testing on Linux systems Brian? 

I usually use either a JUnit test, or do interactive tests like your test.  I've never had any problems running them on Ubuntu Linux.  Of course that's a full Ubuntu installation with graphics drivers and everything.  I don't know much about what would be different on a minimal linux installation, and whether there would be drivers or anything missing the IJ needs. 

> Also, I'm not sure what's up with the travis CI build error. Is the "org.bytedeco.javacpp-presets" artifact for ops-experiments-main not being found like that something you've seen before?

No, but I might of caused it when I refactored the project to be multi-module.   I'll take at it later tonight or tomorrow and get it fixed.

**Comment by bnorthan** [comment]
Hi Eric

I took a quick look at the ```ops-experiments-main``` and it still works for me.  You actually have to have the cuda toolkit, and mkl libraries installed on your machine, in the default location for the build to work, so I expected it fail when building the native libraries (via maven).   However it looks like it's failing earlier than that, because it can't find one of the java-cpp presets artifacts.  I'm attending a hackathon this week and I hope make this my main project.  I want to further modulize ops-experiments-main into cuda, mkl, and a java only sub-project then do some benchmarks on the underlying FFTs, math libraries, and the Richardson Lucy implementations.   I'm curious whether the tensor-flow version will be just as fast as a pure cuda version of Richardson Lucy, or if there is any overhead with it.   If the former, that would be really exciting, as interacting with the GPU through tensorflow seems like it might be easier then maintaining native code.

**Comment by eric-czech** [comment]
Ah ok perfect, thanks @imagejan I'll switch it to that dependency instead.

Sounds good @bnorthan !  I know I'd be surprised if it's as fast as some pure cuda code for something like this though I'd also be surprised if it was more than say 15% or so slower.  The API is pretty awesome to work with though given how comprehensive it is these days.

Also, the biggest overhead with it is likely to be reading in the graph definition from a file and initializing a "session".  Normally, you'd do that once and then run all your computations before closing the session, but in this case it's all happening every time the op is called.  I wasn't sure how to manage state between calls to an op so I figured the extra slowness was worth avoiding the risk of resource leaks but let me know if there's already a framework in place for controlling things like that.

**Comment by bnorthan** [comment]
I merged your pull request and am going to work on some benchmarks today. 

I also refactored the cuda code into a separate module (ops-experiments-cuda) the only pre-requisite for it to compile should be having the cuda libraries installed in the default location (/usr/local/cuda-9.1/lib64/).  So if you get a chance give that another try and let me know if it works for you.  You should be able to run the entire build process with just ```mvn``` (it will call a bash script that does the native build) then run the test using ```mvn exec:java -Dexec.mainClass="net.imagej.ops.experiments.filter.deconvolve.InteractiveDeconvolveTest"
```

**Comment by bnorthan** [comment]
Hi Eric

I added another test for FlowDec [here](https://github.com/imagej/ops-experiments/blob/master/ops-experiments-tensorflow/src/main/java/net/imagej/ops/experiments/filter/deconvolve/InteractiveTensorFlowDeconvolveTest.java).  It uses the same test image and settings (100 iterations, 20 pixel borders) as a [Cuda](https://github.com/imagej/ops-experiments/blob/master/ops-experiments-cuda/src/main/java/net/imagej/ops/experiments/filter/deconvolve/InteractiveCudaDeconvolveTest.java) and [MKL](https://github.com/imagej/ops-experiments/blob/master/ops-experiments-mkl/src/main/java/net/imagej/ops/experiments/filter/deconvolve/InteractiveMKLDeconvolveTest.java) test.  

The FlowDec version ran fine in CPU mode, however it was much slower than I expected, the pure MKL version was ~35 seconds, and the FlowDec version ~700 seconds.  Perhaps I am doing something wrong in the test, let me know if so.  Or perhaps it is doing something sub-optimal when extending the image??  I am adding the border and then extending further to the next power of 2, so I end up with a 256 by 256 by 256 volume.  
n extending the image??  I am adding the border and then extending further to the next power of 2, so I end up with a 256 by 256 by 256 volume.  

I also tried to run with ```-P gpu```, however I ran into an issue where it was looking for version 9.0 of cuda and I have version 9.1 on my system.   Just for reference the Cuda version runs in about 5 seconds for me.

**Comment by eric-czech** [comment]
Hmm well at first glance it's operating the same way in that test, adding the borders and then rounding up to the next power of 2.  For example, if you override the default power of 2 padding by setting padMode to 'none' it ends up being a lot slower still than what you were seeing on a CPU.

I'll mess with it a bit soon and see if I can find something about execution on cpus that can be improved (have not tested that much at all).  And I'll try to get that other artifact building to get a GPU comparison.

**Comment by eric-czech** [comment]
Ha nm, working getting the correct cuda toolkit for nvcc

**Comment by bnorthan** [comment]
Hi Eric

I think the tensor flow approach makes a lot of sense.  Especially considering how easy it seems to build and call using Java bindings.  Quick question.   When trying to run your code I get an error because it is looking for Cuda 9.0 (I have 9.1).  Is there a way to fix that??  Or do I have to install 9.0??

**Comment by bnorthan** [comment]
OK.  So maybe I should build ops-experiments-cuda against 9.0, so it's easy to make both on the same machine.  I'll try to do that tomorrow and do some more testing.

**Comment by bnorthan** [comment]
Hi Erica 

I switched to cuda 9.0 and now it's complaining that it can't find /tmp/tensorflow_native_libraries-1524929489166-0/libtensorflow_jni.so.  Should maven have taken care of that for me??  Or do I have to install a tensor flow library??  If so, and when you get a chance let me know which one and how do I install on Ubuntu 16.04??

**Comment by eric-czech** [comment]
Hm yea sorry, I'm not sure what's going on there assuming CUDA Toolkit and cuDNN are all setup (per the usual [TensorFlow GPU Setup Instructions](https://www.tensorflow.org/install/install_linux)).  Maybe it has something to do with cuDNN?  You shouldn't have to do anything outside of those things, or at least I didn't need to on 16.04.

What do you get from something like this ? ([source](https://medium.com/@changrongko/nv-how-to-check-cuda-and-cudnn-version-e05aa21daf6c))

```
cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
or
cat /usr/include/cudnn.h | grep CUDNN_MAJOR -A 2
```

And did ```mvn install -P gpu``` work ok before trying to run the test?

**Comment by bnorthan** [comment]
Hi Eric

Do you have to install the developement version of CUDNN to get this to work from maven??  That's OK.  Just confirming.  I installed the runtime libraries but still don't have cudnn.h probably because I did not install the development version .   It still doesn't work as it is complaining about missing libraries. 

In the documentation you linked to it says - cuDNN v7.0. For details, see NVIDIA's documentation. Ensure that you create the CUDA_HOME environment variable as described in the NVIDIA documentation.".  I couldn't see anything about the CUDA_HOME variable.  Do you know what that is suppose to be set to.  

Also is libcupti-dev (part of cuda command tools) an absolute requirement for running your examples?  The instructions on the tensorflow site don't seem to work for installing this library.

**Comment by bnorthan** [comment]
Hi Eric

I got it to work by purging all things nvidia then following this guide here https://yangcha.github.io/CUDA90/

The instructions from the tensorflow page didn't work.  The first time I ran it, it took a few minutes.  I wonder if it was doing some system initialization or something??  The second time I ran it, it was about 7 seconds or so on my GTX960M.   I'm hoping to get time to play with a AWS instance with more firepower next week.  This is really nice work.  Thanks a lot for contributing it.  

> Things look pretty good on a GPU though so perhaps there's still a chance this makes sense given that Tensorflow has nice installers for different platforms? I'm not sure but let me know what you think would make sense next.

I think the step is to run some more tests on different images, and closely compare the results between the different versions of RL, to see if there are any unexpected differences.  At the same time perhaps we can think of ways to set up some of the experiments (PSF size, validating quality of decon results, etc.) that you've been talking about on the listserv.  Let me know.

**Comment by eric-czech** [comment]
Nice (sorry for the delay)!  I had started a while ago [Comparing to DL2 on their benchmark datasets](https://github.com/hammerlab/flowdec/blob/master/python/examples/notebooks/Quality%20Measurement%20-%20Benchmarking.ipynb) but would love to potentially try adding YacuDecu to that evaluation at some point too.  If nothing else, on those datasets I could get fairly equal (at least to ~.1 of a score unit for **DL2-Defaults** vs **Flowdec-Matching**) ssim, psnr and nrmse scores when making the arguments match, with some other arguments added there to give some sense of variation.

If you have some ideas for experiments, I'm all ears though.  Do you know of any other good benchmark datasets off the top of your head that would be worth testing?

**Comment by bnorthan** [comment]
Hi Eric, I have a few publicly available images I've collected over the years, and I've been meaning to post them somewhere so we can retrieve them by a URL, and integrate them into reproducible tests.  To  I start with I've added some more small test images cropped from BIG Lab images.  The C-Elegans image is a good test as the structure extends beyond the boundaries, so edge handling may become important.  I added a class to load the images, preprocess them, and generate a theoretical PSF if needed.  You can see how it works [here](https://github.com/imagej/ops-experiments/tree/master/ops-experiments-common/src/main/java/net/imagej/ops/experiments/testImages).  I tried testing your Tensorflow code with the new images [here](https://github.com/imagej/ops-experiments/blob/master/ops-experiments-tensorflow/src/main/java/net/imagej/ops/experiments/filter/deconvolve/InteractiveTensorFlowDeconvolveTest.java#L53) but an assertion was raised because it looks like your code wants the images to be 16 bit unsigned.

**Comment by imagejan** [comment]
@bnorthan wrote:
> I've been meaning to post them somewhere so we can retrieve them by a URL

I guess we can serve sample image data from `imagej.net` if you like. (@ctrueden ?)

**Comment by ctrueden** [comment]
https://samples.fiji.sc/ ?

**Comment by eric-czech** [comment]
Hm well it does ultimately expect only non-negative float values but doesn't do any explicit type checking, so I'm not sure how that's possible given that test class -- any chance you have the trace from it? 

I'll try the copy of the c. elegans image I have at some point soon but in the meantime, if you still have the error details, let me know.  Thanks!

**Comment by eric-czech** [comment]
After pulling the latest master branch, I keep getting this with test classes like that:

```
Exception in thread "main" java.lang.UnsupportedOperationException: Attempting to read or write from a io.scif.io.VirtualHandle. There is no source to operate on.
	at io.scif.io.VirtualHandle.read(VirtualHandle.java:83)
	at io.scif.io.RandomAccessInputStream.read(RandomAccessInputStream.java:437)
	at io.scif.formats.KontronFormat$Checker.isFormat(KontronFormat.java:124)
	at io.scif.AbstractChecker.isFormat(AbstractChecker.java:93)
	at io.scif.services.DefaultFormatService.getFormatList(DefaultFormatService.java:342)
	at io.scif.services.DefaultFormatService.getFormat(DefaultFormatService.java:317)
	at io.scif.services.DefaultInitializeService.initializeReader(DefaultInitializeService.java:89)
	at io.scif.img.ImgOpener.createReader(ImgOpener.java:561)
	at io.scif.img.ImgOpener.openImgs(ImgOpener.java:144)
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:126)
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:111)
	at io.scif.services.SCIFIODatasetService.open(SCIFIODatasetService.java:165)
	at net.imagej.ops.experiments.filter.deconvolve.InteractiveTensorFlowDeconvolveTest.main(InteractiveTensorFlowDeconvolveTest.java:68)
[ERROR] Module threw error
java.lang.NoClassDefFoundError: net/imglib2/roi/geometric/Polygon
	at net.imagej.ops.geom.geom2d.LabelRegionToPolygonConverter.getOutputType(LabelRegionToPolygonConverter.java:77)
	at org.scijava.convert.AbstractConvertService.getCompatibleOutputClasses(AbstractConvertService.java:153)
	at net.imagej.display.process.SingleInputPreprocessor.getSingleInput(SingleInputPreprocessor.java:102)
	at net.imagej.display.process.SingleInputPreprocessor.process(SingleInputPreprocessor.java:81)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:105)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:157)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.imglib2.roi.geometric.Polygon
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
```

Have you not run into that too?  I'm not overriding any managed versions or anything so I'm not sure what might have changed.

**Comment by bnorthan** [comment]
Hi @eric-czech 

I haven't run into that.  It looks like it can't find the files.  However, as far as I can tell, the only code I [changed](https://github.com/imagej/ops-experiments/commit/2dc6fcba052ad61a77111edb21821cd6e9ef3f73#diff-3d0fefbce80444cc744817dbd5e515f7), I commented out because it wasn't functioning yet.  So unless I'm having a brain cramp, and can't see something I messed up (always possible), the code should function exactly the same. 

The files are defined as follows...

final String imgPath = "../images/Bars-G10-P15-stack-cropped.tif";
final String psfPath = "../images/PSF-Bars-stack-cropped.tif";

Are you potentially running the test from a different directory so the local path isn't working??

**Comment by eric-czech** [comment]
Ah whoops, yep it was an incorrect path and after fixing it I still get ```java.lang.NoClassDefFoundError: net/imglib2/roi/geometric/Polygon``` errors but it looks like they're not critical because it still runs.

I then tried ```testData = new CElegans()``` as well as ```testData = new Bars()``` which both worked fine but ```testData = new HalfBead()``` failed with an error like:

```
Exception in thread "main" java.lang.IllegalArgumentException: assertion failed: [41 128 128] [128 128 128]
	 [[Node: assert_greater_equal/Assert/Assert = Assert[T=[DT_INT32, DT_INT32], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](assert_greater_equal/All, Shape_2, Shape_3)]]
	at org.tensorflow.Session.run(Native Method)
        ...
```

I assume that's what you saw too right?  There may be a way to have TensorFlow spit out something more informative but what it's saying is that it expects the dimensions of the PSF to be less than or equal to that of the image which is apparently not true for ```HalfBead``` where the PSF is 128x128x128 and the image 41x128x128.

Was that intentional for the PSF to have more z-planes for that dataset?  I was imagining that wouldn't be a common scenario so I made some simplifying assumptions based on it and put that check in to be safe.

**Comment by bnorthan** [comment]
I just changed the HalfBead() example to use a smaller PSF and pushed it.   So there are differences between the Cuda and the Tensorflow implementation for the CElegans image and the HalfBead, it may have to do with edge handling.  How are you handling edges??  I am using the non-circulant approach described at the [2014 Deconvolution Grand Challenge](http://bigwww.epfl.ch/deconvolution/challenge/index.html?p=documentation/theory/richardsonlucy)

**Comment by eric-czech** [comment]
Ah yea for that I was mirroring the image outside of the borders and assuming a block-circulant PSF (like DL2) so it's probably not as good.

**Comment by imagejan** [comment]
@eric-czech wrote:

> `java.lang.NoClassDefFoundError: net/imglib2/roi/geometric/Polygon`

This is likely due to version mismatches between `imglib-roi` and `imagej-ops` that were present in `pom-scijava` version 20.0.0 (which you are currently using):

https://github.com/imagej/ops-experiments/blob/a10349782c9457ecff42c150d0a27e643e657c0a/pom.xml#L9

I suggest updating the parent `pom-scijava` version to `21.0.0`.

**Comment by eric-czech** [comment]
Thanks @imagejan , I tried updating that version locally but still got that same error.  Probably not a big deal though if you're not seeing that too Brian.

By the way @bnorthan , do you have a ground truth image for the Bead or HalfBead datasets?  Or do you know how to make one?

**Comment by bnorthan** [comment]
Hi @eric-czech, the BIg Lab website notes that the diameters of the bead is 2.5 um.  You could calculate the volume of the bead, then apply a threshold, followed by segmenation and volume measurement to the original and deconvolved images, then you can evaluate deconvolution by the difference between expected volume and measured volume.    I just manually cropped the bead to make the half bead, so for that one I'll have to double check to make sure I cropped it at the center, then assume the volume is half the volume of the full bead.

**Comment by ctrueden** [comment]
> `java.lang.NoClassDefFoundError: net/imglib2/roi/geometric/Polygon`

Sorry for this. Make sure you have imglib2-roi 0.5.0 or newer, and imagej-ops 0.40.0 or newer. As @imagejan says, using pom-scijava 21.0.0 as parent should include these. If you are still seeing that error, make sure you have no version overrides—either as `<version>...</version>` elements in your dependencies, or as `<imagej-ops.version>...</imagej-ops.version>` in your properties.

**Pull request merged**
